version: '3.9'
services:
  triton:
    build:
      context: ./triton-custom
      dockerfile: Dockerfile.triton-custom
    image: triton-custom:22.12
    command: tritonserver --model-repository=/models --http-port=8081
    shm_size: "48g"
    environment:
      TRITONSERVER_DISABLE_AVX_CHECK: "1"
      HF_HOME: /opt/hf-cache
      HF_HUB_CACHE: /opt/hf-cache
      TRANSFORMERS_CACHE: /opt/hf-cache
    volumes:
      - /srv/models:/models:ro
      - /srv/hf-cache:/opt/hf-cache
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  ml-gateway:
    build:
      context: ./ml-gateway-app         # путь к Dockerfile
    environment:
      TRITON_HTTP: http://triton:8081
    depends_on: [triton]
    ports:
      - "8090:80"                   # наружу
